# -*- coding: utf-8 -*-
"""Level3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tfw_kX7bw2Sj2dUqYdF8v0CNdoNYwuJ4
"""

# Load dependencies
import json
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
import shutil
from torchvision import models
import matplotlib.pyplot as plt
import numpy as np
from pycocotools.coco import COCO
import random

drive.mount('/content/drive')

# My Drive paths
BASE_DIR_DRIVE = '/content/drive/MyDrive/5.Projects'
DATA_DIR_DRIVE = os.path.join(BASE_DIR_DRIVE, "Data", "ShipRSImageNet_V1")

# Local Colab storage paths to speed up training considerably
BASE_DIR_LOCAL = '/content/5.Projects'
DATA_DIR_LOCAL = os.path.join(BASE_DIR_LOCAL, "Data", "ShipRSImageNet_V1")



if os.path.exists(DATA_DIR_LOCAL):
    print("Local already exists")
else:
    os.makedirs(os.path.dirname(DATA_DIR_LOCAL), exist_ok=True)
    shutil.copytree(DATA_DIR_DRIVE, DATA_DIR_LOCAL)

# reset to use local
DATA_DIR = DATA_DIR_LOCAL

TRAIN_JSON = os.path.join(DATA_DIR, "COCO_Format", "ShipRSImageNet_bbox_train_level_3.json")
VAL_JSON   = os.path.join(DATA_DIR, "COCO_Format", "ShipRSImageNet_bbox_val_level_3.json")
TEST_JSON = os.path.join(DATA_DIR, "COCO_Format", "ShipRSImageNet_bbox_test_level_3.json")
IMG_DIR    = os.path.join(DATA_DIR, "VOC_Format", "JPEGImages")

# Define a function to extract the labels from the COCO JSON files

# We will take one label per image, as we train on one level at a time
def coco_to_image_labels(coco_json):
    # open and parse JSON
    with open(coco_json) as f:
        data = json.load(f)

    # create mappings for images and assigned categories
    images = {img["id"]: img["file_name"] for img in data["images"]}
    categories = {cat["id"]: cat["name"] for cat in data["categories"]}

    # map image IDs to list of category IDs
    img_to_cats = {}
    for ann in data["annotations"]:
        img_to_cats.setdefault(ann["image_id"], []).append(ann["category_id"])

    # Build the dataframe to have one label per image per row
    records = []
    for img_id, fname in images.items():
        if img_id in img_to_cats:
            cat_ids = img_to_cats[img_id]
            main_cat = max(set(cat_ids), key=cat_ids.count)
            records.append({"filename": fname, "label": categories[main_cat]})
    return pd.DataFrame(records)

# Run for train and val DFs
train_df = coco_to_image_labels(TRAIN_JSON)
val_df   = coco_to_image_labels(VAL_JSON)

# Inspect training
print(train_df.head(30))
print("Classes:", train_df["label"].unique())

# Basically, I used the documentation of the 'transforms' package and threw the kitchen sink at the data augmentation step to see what happens
# https://docs.pytorch.org/vision/stable/transforms.html
# https://docs.pytorch.org/vision/main/generated/torchvision.transforms.ToTensor.html
# https://docs.pytorch.org/vision/stable/generated/torchvision.transforms.v2.RandomErasing.html

train_transform = transforms.Compose([
    transforms.Resize(256), # Resize to 256 before cropping down again
    transforms.RandomCrop(224), # Crop
    transforms.RandomVerticalFlip(0.5), # Flips, rotation, invert
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomInvert(p=0.1),
    transforms.RandomRotation(0.5),
    transforms.ToTensor(),  # tensor transformation
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), # and normalization to levels I found in documnetation
])

# Validation normalization to same levels

val_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class ShipImageDataset(Dataset):
    def __init__(self, df, image_dir, transform=None):
        self.df = df.reset_index(drop=True)
        self.image_dir = image_dir
        self.transform = transform
        self.classes = sorted(df["label"].unique())
        self.class_to_idx = {c: i for i, c in enumerate(self.classes)}

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.image_dir, row["filename"])
        img = Image.open(img_path).convert("RGB")                               # Creates RGB pillow Image
        label = self.class_to_idx[row["label"]]
        if self.transform:                                                      # Applies the actual transformation from pillow Image to tensor
            img = self.transform(img)
        return img, torch.tensor(label, dtype=torch.long)

# Actual transformation
train_ds = ShipImageDataset(train_df, IMG_DIR, train_transform)
val_ds   = ShipImageDataset(val_df, IMG_DIR, val_transform)

# Lets inspect the new Train and Val DataSets

print(type(train_ds))
print(type(val_ds))
print("Number of training samples:", len(train_ds))
print("Number of validation samples:", len(val_ds))



print("Total samples:", len(train_ds))
print("Classes:", train_ds.classes)
print("Class → index mapping:", train_ds.class_to_idx)

# Inspect one sample

# Grabbing image and label from the first row


img, label = train_ds[0]
print("Type of img:", type(img))
print("Shape of img:", img.shape)
print("Type of label:", type(label))
print("Value of label:", label)

print(f"We can see that the image is now a tensor, and the label is also a tensor")

mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
std  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

img_np = img.detach().cpu().numpy().transpose(1, 2, 0)  # [C,H,W] -> [H,W,C]
img_np = (img_np * std + mean).clip(0, 1)

plt.imshow(img_np)
plt.title(f"Label: {train_ds.classes[label.item()]}")
plt.axis("off")
plt.show()

# We pass the DataSet objects to the DataLoader
# This is also where we define the batch size and whether to shuffle the training data
# After each batch, we update the model weights

train_dl = DataLoader(train_ds, batch_size=32, shuffle=True)
val_dl   = DataLoader(val_ds, batch_size=32, shuffle=False)

imgs, labels = next(iter(train_dl))  # grabs the first batch
print("Batch shape:", imgs.shape)
print("Labels shape:", labels.shape)
print("Labels (as numbers):", labels.tolist())

# Unnormalize and inspect some images + labels
imgs, labels = next(iter(train_dl))

mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
std  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

fig, axes = plt.subplots(2, 4, figsize=(12, 6))
for i, ax in enumerate(axes.flat):
    img = imgs[i].detach().cpu().numpy().transpose(1, 2, 0)
    img = (img * std + mean).clip(0, 1)
    ax.imshow(img)
    ax.set_title(train_ds.classes[labels[i].item()])
    ax.axis("off")

plt.tight_layout()
plt.show()

"""# Small Model"""

class Net(nn.Module):
    def __init__(self):                             # CONV LAYER SETUP: (Input channels (RGB), output channels (filter number), kernel size (filter size))
        super().__init__()
        self.conv1 = nn.Conv2d(3, 8, 3)             # First CONV LAYER: We will start out with 8 filters, at kernel size 3. So each filter will be 3 x 3 x 3
        self.pool1 = nn.MaxPool2d(2, 2)              # First POOLING LAYER: MaxPooling at 2 x 2
        self.conv2 = nn.Conv2d(8, 16, 3)            # Second CONV LAYER: Input channels = last lauyer's output channels, double to 16 filters, keep filter size
        self.pool2 = nn.MaxPool2d(2, 2)             # Second POOLING LAYER: MaxPooling at 2 x 2
        self.conv3 = nn.Conv2d(16, 32, 3)           # Third CONV LAYER: Input channels = last lauyer's output channels, double to 32 filters, keep filter size
        self.fc1 = nn.Linear(32 * 52 * 52, 48)

    def forward(self, x):                           # This is the forward pass step
        x = self.pool1(F.relu(self.conv1(x)))      # First CONV, RELU, POOL
        x = self.pool2(F.relu(self.conv2(x)))      # Second CONV, RELU, POOL
        x = F.relu(self.conv3(x))                  # Third CONV, RELU NO POOL since last layer
        x = torch.flatten(x, 1)                     # Flatten all dimensions except batch
        x = self.fc1(x)                             # Fully connected layer
        return x

net = Net()

loss_function = nn.CrossEntropyLoss() # For multi-class classification
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9) # Stochastic Gradient Descent to update weights after each batch
# Low learning rate and momentum to avoid overshooting, this will impact training time

import json
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net.to(device)

# Fitting just 10 epochs for now
num_epochs = 30

# Initialize empty lists for metrics
train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []

# Also, initiate an updating count of the best current Val ACC, so we can update
best_val_acc = 0.0

# Save paths
BASE_DIR_DRIVE = '/content/drive/MyDrive/5.Projects'
models_dir = os.path.join(BASE_DIR_DRIVE, 'models')
os.makedirs(models_dir, exist_ok=True)

best_model_path = os.path.join(models_dir, 'best_model_Net_Level3.pth')
final_model_path = os.path.join(models_dir, 'final_model_Net_Level3.pth')
history_path = os.path.join(models_dir, 'Net_history_Level3.json')

# set up the training loop
for epoch in range(num_epochs):


    # set model to training
    net.train()
    running_loss = 0.0
    correct = 0
    total = 0

    # for each batch, send data inputs and labels to device, zero gradients, forward pass, compute loss, backward pass, optimize
    for inputs, labels in train_dl:
        inputs, labels = inputs.to(device), labels.to(device) # inputs and labels
        optimizer.zero_grad() # optimizer
        outputs = net(inputs) # Send through our Net architecture
        loss = loss_function(outputs, labels) # compute loss
        loss.backward() # backward pass
        optimizer.step() # apply optimizer

        # THIS IS ONE EPOCH


        # accumulate loss and accuracy
        running_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (preds == labels).sum().item()

    # compute epoch loss and accuracy
    train_loss = running_loss / len(train_dl)
    train_acc = 100 * correct / total

    # set model to evaluation and run eval pass:
    net.eval()
    val_running_loss = 0.0
    val_correct = 0
    val_total = 0


    # same as above minus the backward pass
    with torch.no_grad():
        for inputs, labels in val_dl:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = net(inputs)
            loss = loss_function(outputs, labels)
            val_running_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (preds == labels).sum().item()


    # Compute Val steps
    val_loss = val_running_loss / len(val_dl)
    val_acc = 100 * val_correct / val_total

    # Append back onto empty lists
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(f"Epoch [{epoch+1:2d}/{num_epochs}]"
          f"  || Train Loss: {train_loss:.4f} || Train Acc: {train_acc:6.2f}%"
          f"  ||  Val Loss: {val_loss:.4f} || Val Acc: {val_acc:6.2f}%", end="")

    # Save best model and assign a label
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(net.state_dict(), best_model_path)
        print("Current Best Model")
    else:
        print()

# Save final model
torch.save(net.state_dict(), final_model_path)

# Save history for plots later
history = {
    'train_losses': train_losses,
    'val_losses': val_losses,
    'train_accuracies': train_accuracies,
    'val_accuracies': val_accuracies,
    'best_val_acc': best_val_acc
}

with open(history_path, 'w') as f:
    json.dump(history, f)

print("Training done")
print(f"Best Val Acc: {best_val_acc:.2f}%")

"""# Big Model"""

# Here, I tried to create a Maximum model and see how it compares.
# I took most of the architecture from VGG: https://medium.com/@siddheshb008/vgg-net-architecture-explained-71179310050f

# Basically:
# 4 Blocks
# Double Conv Layer for 1. and 2. Block, triple Conv layer for 3. and 4th Block. Also taken from VGG, as 16 and 19 have this architecture
# Normalize each Batch: https://docs.pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html
# 1 Pool layer for each Block
# Final layer at 512 filters
# 3 Fully Connected Layers
# Dropout rate mostly at 0.5 for the FCs
# Global Average Pooling (Also helped prevent model collaps)
# Forward uses ReLu for Batch Norm and Conv Layers



# I ran into major troubles with the model collapsing
# Hinestly, I did not know what to change and asked Claude AI for each
# I then integrated the re-construction function to counter this, but take no credit for it




class Net_Max(nn.Module):

    def __init__(self, num_classes=48, dropout_rate=0.5):
        super().__init__()

        # Block 1: 64 filters
        self.conv1a = nn.Conv2d(3, 64, kernel_size=3, padding=1)
        self.bn1a = nn.BatchNorm2d(64)
        self.conv1b = nn.Conv2d(64, 64, kernel_size=3, padding=1)
        self.bn1b = nn.BatchNorm2d(64)
        self.pool1 = nn.MaxPool2d(2, 2)

        # Block 2: 128 filters
        self.conv2a = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn2a = nn.BatchNorm2d(128)
        self.conv2b = nn.Conv2d(128, 128, kernel_size=3, padding=1)
        self.bn2b = nn.BatchNorm2d(128)
        self.pool2 = nn.MaxPool2d(2, 2)

        # Block 3: 256 filters (3 conv layers)
        self.conv3a = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.bn3a = nn.BatchNorm2d(256)
        self.conv3b = nn.Conv2d(256, 256, kernel_size=3, padding=1)
        self.bn3b = nn.BatchNorm2d(256)
        self.conv3c = nn.Conv2d(256, 256, kernel_size=3, padding=1)
        self.bn3c = nn.BatchNorm2d(256)
        self.pool3 = nn.MaxPool2d(2, 2)

        # Block 4: 512 filters (3 conv layers) - NEW!
        self.conv4a = nn.Conv2d(256, 512, kernel_size=3, padding=1)
        self.bn4a = nn.BatchNorm2d(512)
        self.conv4b = nn.Conv2d(512, 512, kernel_size=3, padding=1)
        self.bn4b = nn.BatchNorm2d(512)
        self.conv4c = nn.Conv2d(512, 512, kernel_size=3, padding=1)
        self.bn4c = nn.BatchNorm2d(512)
        self.pool4 = nn.MaxPool2d(2, 2)

        # Global Average Pooling
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Classification head
        self.fc1 = nn.Linear(512, 256)
        self.dropout1 = nn.Dropout(dropout_rate)
        self.fc2 = nn.Linear(256, 128)
        self.dropout2 = nn.Dropout(dropout_rate)
        self.fc3 = nn.Linear(128, num_classes)

        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        # Block 1
        x = F.relu(self.bn1a(self.conv1a(x)))
        x = F.relu(self.bn1b(self.conv1b(x)))
        x = self.pool1(x)

        # Block 2
        x = F.relu(self.bn2a(self.conv2a(x)))
        x = F.relu(self.bn2b(self.conv2b(x)))
        x = self.pool2(x)

        # Block 3
        x = F.relu(self.bn3a(self.conv3a(x)))
        x = F.relu(self.bn3b(self.conv3b(x)))
        x = F.relu(self.bn3c(self.conv3c(x)))
        x = self.pool3(x)

        # Block 4
        x = F.relu(self.bn4a(self.conv4a(x)))
        x = F.relu(self.bn4b(self.conv4b(x)))
        x = F.relu(self.bn4c(self.conv4c(x)))
        x = self.pool4(x)

        # Classification
        x = self.global_pool(x)
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = self.dropout1(x)
        x = F.relu(self.fc2(x))
        x = self.dropout2(x)
        x = self.fc3(x)
        return x

# Create model Call
net_Max = Net_Max(num_classes=48, dropout_rate=0.5)

# Setup device and move model to GPU, this is from when I set it all up on my local
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net_Max.to(device)

print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# optimizer and loss function
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(net_Max.parameters(), lr=0.001)

# 4. Training params
num_epochs = 30
train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []
best_val_acc = 0.0

# Save model history
# Save paths
BASE_DIR_DRIVE = '/content/drive/MyDrive/5.Projects'
models_dir = os.path.join(BASE_DIR_DRIVE, 'models')
os.makedirs(models_dir, exist_ok=True)

best_model_path = os.path.join(models_dir, 'best_model_Net_Max_Level3.pth')
final_model_path = os.path.join(models_dir, 'final_model_Net_Max_Level3aug.pth')
history_path = os.path.join(models_dir, 'Net_Max_history_Level3.json')

print("Training Max Model Net_Max")


# Takes same logic as above

for epoch in range(num_epochs):
    # TRAINING
    net_Max.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, labels in train_dl:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = net_Max(inputs)
        loss = loss_function(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (preds == labels).sum().item()

    train_loss = running_loss / len(train_dl)
    train_acc = 100 * correct / total

    # VALIDATION
    net_Max.eval()
    val_running_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for inputs, labels in val_dl:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = net_Max(inputs)
            loss = loss_function(outputs, labels)
            val_running_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (preds == labels).sum().item()

    val_loss = val_running_loss / len(val_dl)
    val_acc = 100 * val_correct / val_total

    # Store metrics
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(f"Epoch [{epoch+1:2d}/{num_epochs}]"
        f"  || Train Loss: {train_loss:.4f} || Train Acc: {train_acc:6.2f}%"
        f"  ||  Val Loss: {val_loss:.4f} || Val Acc: {val_acc:6.2f}%", end="")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(net_Max.state_dict(), best_model_path)
        print("Current Best Model")
    else:
        print()

# Save final model
torch.save(net_Max.state_dict(), final_model_path)

# Save history
history = {
    'train_losses': train_losses,
    'val_losses': val_losses,
    'train_accuracies': train_accuracies,
    'val_accuracies': val_accuracies,
    'best_val_acc': best_val_acc
}

with open(history_path, 'w') as f:
    json.dump(history, f)

print("Training Done")
print(f"Best Val Acc: {best_val_acc:.2f}%")

"""# ResNet

Now, lets get ResNet and Fine tune on the images

I expect this to be much much better
"""

ResNet = models.resnet101(pretrained=True)

# Most important part is to set pre_trained to True so we dont retrain.
# We just want to fine tune

# Get ResNet101 because why not

num_ftrs = ResNet.fc.in_features  # grab features from the pre-trained body so we can adjust from there
ResNet.fc = nn.Linear(num_ftrs, 48)

# Move model to GPU
ResNet.to(device) # send to device GPU

# Optimizer and loss
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(ResNet.parameters(), lr=0.0001)

# Training parameters, same logic as above
num_epochs = 30
train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []
best_val_acc = 0.0

# Save paths again
BASE_DIR_DRIVE = '/content/drive/MyDrive/5.Projects'
models_dir = os.path.join(BASE_DIR_DRIVE, 'models')
os.makedirs(models_dir, exist_ok=True)

best_model_path = os.path.join(models_dir, 'best_model_ResNet_Level3.pth')
final_model_path = os.path.join(models_dir, 'final_model_ResNet_Level3.pth')
history_path = os.path.join(models_dir, 'ResNet_history_Level3.json')

print("Fine Tuning ResNet")

for epoch in range(num_epochs):
    # TRAINING
    ResNet.train() # Again, we train as we are not just adjusting the classifier head
    running_loss = 0.0
    correct = 0
    total = 0



# Fine Tune is the same as above
    for inputs, labels in train_dl: # Here is where we bring my Train Dataset of the ships with the DataLoader
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad() # Restet the gradients again
        outputs = ResNet(inputs) # Forward pass on all ResNet layers
        loss = loss_function(outputs, labels) # Compute Loss on DataSet Image Labels
        loss.backward() # Compute gradients
        optimizer.step() # Update all weights based on Ship Labels

        running_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (preds == labels).sum().item()

    train_loss = running_loss / len(train_dl)
    train_acc = 100 * correct / total

    # VALIDATION
    ResNet.eval()
    val_running_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for inputs, labels in val_dl:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = ResNet(inputs)
            loss = loss_function(outputs, labels)
            val_running_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (preds == labels).sum().item()

    val_loss = val_running_loss / len(val_dl)
    val_acc = 100 * val_correct / val_total

    # Store metrics
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(f"Epoch [{epoch+1:2d}/{num_epochs}]"
          f"  || Train Loss: {train_loss:.4f} || Train Acc: {train_acc:6.2f}%"
          f"  ||  Val Loss: {val_loss:.4f} || Val Acc: {val_acc:6.2f}%", end="")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(ResNet.state_dict(), best_model_path)
        print("Current Best Model")
    else:
        print()

# Save final model
torch.save(ResNet.state_dict(), final_model_path)

# Save history
history = {
    'train_losses': train_losses,
    'val_losses': val_losses,
    'train_accuracies': train_accuracies,
    'val_accuracies': val_accuracies,
    'best_val_acc': best_val_acc
}

with open(history_path, 'w') as f:
    json.dump(history, f)

print("Training Done")
print(f"Best Val Acc: {best_val_acc:.2f}%")

"""# Visualize"""

# Lets access the model history stats

BASE_DIR_DRIVE = '/content/drive/MyDrive/5.Projects'
models_dir = os.path.join(BASE_DIR_DRIVE, 'models')

with open(os.path.join(models_dir, 'Net_history_Level3.json'), 'r') as f:
    net_history = json.load(f)

with open(os.path.join(models_dir, 'Net_Max_history_Level3.json'), 'r') as f:
    net_max_history = json.load(f)

with open(os.path.join(models_dir, 'ResNet_history_Level3.json'), 'r') as f:
    resnet_history = json.load(f)

"""# Training Accuracy Across all Models"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Training Accuracy
ax1.plot(net_history['train_accuracies'], label='Net', linewidth=2.5, alpha=0.8)
ax1.plot(net_max_history['train_accuracies'], label='Net_Max', linewidth=2.5, alpha=0.8)
ax1.plot(resnet_history['train_accuracies'], label='ResNet', linewidth=2.5, alpha=0.8)
ax1.set_xlabel('Epoch', fontsize=13)
ax1.set_ylabel('Accuracy (%)', fontsize=13)
ax1.set_title('Training Accuracy Comparison', fontsize=15, fontweight='bold')
ax1.legend(fontsize=12, loc='lower right')
ax1.grid(True, alpha=0.3)

# Validation Accuracy
ax2.plot(net_history['val_accuracies'], label='Net', linewidth=2.5, alpha=0.8)
ax2.plot(net_max_history['val_accuracies'], label='Net_Max', linewidth=2.5, alpha=0.8)
ax2.plot(resnet_history['val_accuracies'], label='ResNet', linewidth=2.5, alpha=0.8)
ax2.set_xlabel('Epoch', fontsize=13)
ax2.set_ylabel('Accuracy (%)', fontsize=13)
ax2.set_title('Validation Accuracy Comparison', fontsize=15, fontweight='bold')
ax2.legend(fontsize=12, loc='lower right')
ax2.grid(True, alpha=0.3)


plt.tight_layout()
plt.savefig(os.path.join(models_dir, 'accuracy_comparison.png'), dpi=150, bbox_inches='tight')
plt.show()

"""# Comparison of Validation Accuracy"""

fig, ax = plt.subplots(figsize=(10, 6))

models = ['Net', 'Net_Max', 'ResNet']
best_accs = [
    net_history['best_val_acc'],
    net_max_history['best_val_acc'],
    resnet_history['best_val_acc']
]

colors = ['#3498db', '#e74c3c', '#2ecc71']
bars = ax.bar(models, best_accs, color=colors, alpha=0.7, edgecolor='black', linewidth=2)

# Add value labels on bars
for bar, acc in zip(bars, best_accs):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{acc:.2f}%',
            ha='center', va='bottom', fontsize=15, fontweight='bold')

ax.set_ylabel('Validation Accuracy (%)', fontsize=13)
ax.set_title('Best Validation Accuracy Comparison', fontsize=15, fontweight='bold')
ax.set_ylim([0, 100])
ax.grid(True, axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(models_dir, 'best_accuracy_bar.png'), dpi=150, bbox_inches='tight')
plt.show()

"""# Running the Best Model on Test"""

models_dir = os.path.join(BASE_DIR_DRIVE, 'models')

class_names = train_ds.classes

best_model_path = os.path.join(models_dir, 'best_model_ResNet_Level3.pth')
history_path = os.path.join(models_dir, 'ResNet_history_Level3.json')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\nUsing device: {device}")

# Load dependencies
import json
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
import shutil
from torchvision import models
import matplotlib.pyplot as plt
import numpy as np
from pycocotools.coco import COCO
import random

ResNet = models.resnet101(pretrained=False)
ResNet.fc = nn.Linear(ResNet.fc.in_features, 48)

ResNet.load_state_dict(torch.load(best_model_path, map_location=device))

ResNet = ResNet.to(device)
ResNet.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_coco = COCO(TEST_JSON)
test_image_ids = list(test_coco.imgs.keys())

print(f"Test images: {len(test_image_ids)}\n")

all_results = []

for idx, img_id in enumerate(test_image_ids):
    img_info = test_coco.imgs[img_id]
    img_path = os.path.join(IMG_DIR, img_info['file_name'])
    img = Image.open(img_path).convert('RGB')

    # Do the acual prediction
    img_tensor = transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = ResNet(img_tensor) # this is the inference step
        probs = torch.softmax(outputs, dim=1)[0]
        conf, pred_idx = torch.max(probs, 0)

    pred_class = class_names[pred_idx.item()]
    pred_conf = conf.item()

    # Store results
    all_results.append({
        'img_id': img_id,
        'filename': img_info['file_name'],
        'img_path': img_path,
        'predicted_class': pred_class,
        'confidence': pred_conf
    })

random_sample = random.sample(all_results, 16)

fig, axes = plt.subplots(4, 4, figsize=(16, 16))
axes = axes.flatten()

for idx, result in enumerate(random_sample):
    img = Image.open(result['img_path']).convert('RGB')

    axes[idx].imshow(img)
    title = f"{result['predicted_class']}\n({result['confidence']:.3f})"
    axes[idx].set_title(title, fontsize=12, fontweight='bold')
    axes[idx].axis('off')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/5.Projects/test_predictions_random16.png', dpi=150, bbox_inches='tight')
plt.show()

print("PREDICTION SUMMARY")

for class_name in class_names:
    count = sum(1 for r in all_results if r['predicted_class'] == class_name)
    pct = 100 * count / len(all_results)
    print(f"{class_name:20s}: {count:3d} ({pct:5.1f}%)")

avg_conf = sum(r['confidence'] for r in all_results) / len(all_results)
print(f"\nAverage confidence: {avg_conf:.3f}")